-- Script de creación de base de datos
-- Sistema Administrativo PSUV 2

CREATE DATABASE IF NOT EXISTS sistema_administrativo;
USE sistema_administrativo;

-- Tabla: USUARIOS
CREATE TABLE IF NOT EXISTS USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_COMPLETO VARCHAR(100) NOT NULL,
    CEDULA VARCHAR(20) UNIQUE NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    NOMBRE_USUARIO VARCHAR(50) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    NIVEL ENUM('admin', 'operador', 'visualizador') DEFAULT 'operador',
    ACTIVO BOOLEAN DEFAULT 1,
    TOKEN_RECUPERACION VARCHAR(255) NULL,
    TOKEN_EXPIRA DATETIME NULL,
    ULTIMA_CONEXION DATETIME NULL,
    ULTIMA_ACTIVIDAD DATETIME NULL,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla: PERSONAS (Sistema de asistencia)
CREATE TABLE IF NOT EXISTS PERSONAS (
    ID_PERSONAS INT AUTO_INCREMENT PRIMARY KEY,
    CEDULAS VARCHAR(20) UNIQUE NOT NULL,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    ACTIVO BOOLEAN DEFAULT 1,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla: SESIONES
CREATE TABLE IF NOT EXISTS SESIONES (
    ID_SESION INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    FECHA DATE NOT NULL,
    HORA_INICIO TIME NOT NULL,
    TIPO VARCHAR(50) NOT NULL
);

-- Tabla: REGISTRO_ASISTENCIA
CREATE TABLE IF NOT EXISTS REGISTRO_ASISTENCIA (
    ID_REGISTRO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PERSONAS INT NOT NULL,
    ID_SESIONES INT NOT NULL,
    MARCACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO VARCHAR(50) DEFAULT 'Presente',
    METODO VARCHAR(50) DEFAULT 'Manual',
    FOREIGN KEY (ID_PERSONAS) REFERENCES PERSONAS(ID_PERSONAS) ON DELETE CASCADE,
    FOREIGN KEY (ID_SESIONES) REFERENCES SESIONES(ID_SESION) ON DELETE CASCADE
);

-- Tabla: RESPALDOS
CREATE TABLE IF NOT EXISTS RESPALDOS (
    ID_RESPALDO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_ARCHIVO VARCHAR(255) NOT NULL,
    VERSION VARCHAR(50) NOT NULL,
    TAMANO INT NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR INT,
    FOREIGN KEY (CREADO_POR) REFERENCES USUARIOS(ID_USUARIO)
);

-- Tabla: REUNIONES
CREATE TABLE IF NOT EXISTS REUNIONES (
    ID_REUNION INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    TIPO_REUNION VARCHAR(255) NOT NULL,
    LUGAR VARCHAR(255) NOT NULL,
    PARROQUIA ENUM('Simon Bolivar', 'Once de Abril', 'Vista al Sol', 'Chirica', 'Dalla Costa', 'Cachamay', 'Universidad', 'Unare', 'Yocoima', 'Pozo Verde', '5 de Julio') NOT NULL,
    RESPONSABLE_NOMBRE VARCHAR(100) NOT NULL,
    RESPONSABLE_CEDULA VARCHAR(20) NOT NULL,
    RESPONSABLE_TELEFONO VARCHAR(15) NOT NULL,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla: LOGS_SISTEMA
CREATE TABLE IF NOT EXISTS LOGS_SISTEMA (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    ACCION VARCHAR(255) NOT NULL,
    TABLA_AFECTADA VARCHAR(50),
    REGISTRO_ID INT,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- Tabla: PERMISOS (Gestión de módulos)
CREATE TABLE IF NOT EXISTS PERMISOS (
    ID_PERMISO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    MODULO VARCHAR(50),
    PUEDE_VER BOOLEAN DEFAULT 1,
    PUEDE_EDITAR BOOLEAN DEFAULT 0,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

-- Datos de prueba
INSERT INTO USUARIOS (NOMBRE_COMPLETO, CEDULA, TELEFONO, NOMBRE_USUARIO, CONTRASENA, NIVEL) 
VALUES ('Administrador Sistema', '12345678', '04120000000', 'admin', '$2y$10$wRBpNMV6cLpUcuo2Im4Pv.IsNDRDGItlH2TR3Hx/L.sZZ4rGoNUXa', 'admin');

INSERT INTO USUARIOS (NOMBRE_COMPLETO, CEDULA, TELEFONO, NOMBRE_USUARIO, CONTRASENA, NIVEL) 
VALUES ('Operador Prueba', '87654321', '04140000000', 'operador', '$2y$10$1W1cscfRB2CCfq4hOMnd.OSHd2fiOnkvYq7jYWF94.XS3KCsmTd2O', 'operador');

-- Personas de prueba
INSERT INTO PERSONAS (CEDULAS, NOMBRES, APELLIDOS) VALUES ('11111111', 'Juan', 'Perez');
INSERT INTO PERSONAS (CEDULAS, NOMBRES, APELLIDOS) VALUES ('22222222', 'Maria', 'Gomez');

-- Sesiones de prueba
INSERT INTO SESIONES (TITULO, FECHA, HORA_INICIO, TIPO) VALUES ('Asamblea General', '2023-10-27', '09:00:00', 'Ordinaria');
INSERT INTO SESIONES (TITULO, FECHA, HORA_INICIO, TIPO) VALUES ('Taller Formacion', '2023-10-28', '14:00:00', 'Capacitacion');

-- Asistencias de prueba
INSERT INTO REGISTRO_ASISTENCIA (ID_PERSONAS, ID_SESIONES, ESTADO) VALUES (1, 1, 'Presente');
INSERT INTO REGISTRO_ASISTENCIA (ID_PERSONAS, ID_SESIONES, ESTADO) VALUES (2, 1, 'Presente');
